ph-ee-g2psandbox:
  ph-ee-engine:
    camunda-platform-helm:
      enabled: false
    elasticsearch:
      enabled: false
    kibana:
      enabled: false

    operations:
      mysql:
        enabled: false

    ph_ee_connector_ams_mifos:
      enabled: false

    ph_ee_connector_mojaloop:
      enabled: false

    kafka:
      enabled: false
    channel:
      enabled: false

    operations_app:
      enabled: false

    operations_web:
      enabled: false

    ph_ee_connector_gsma:
      enabled: false

    ph_ee_connector_slcb:
      enabled: false

    mpesa:
      enabled: false

    roster_connector:
      enabled: false

    paygops_connector:
      enabled: false

    notifications:
      enabled: false

    connector_bulk:
      enabled: false

    connector_bulk_closedloop:
      enabled: false
    zeebe_ops:
      enabled: false

    messagegateway:
      enabled: false

    importer_es:
      enabled: false

    importer_rdbms:
      enabled: false

    redis:
      enabled: false
    mockpayment:
      enabled: false
    wildcardhostname: "*.sandbox.fynarfin.io"
    tls: ""

    keycloak:
      enabled: true
      ingress:
        enabled: true
        rules:
          - host: 'keycloak.sandbox.fynarfin.io'
            paths:
            - path: /
              pathType: Prefix


    kong:
      enabled: true
      admin:
        enabled: true
        ingress:
          enabled: true
          hostname: admin-kong.sandbox.fynarfin.io
      env:
        pg_host: "dev1-postgresql"
