ph-ee-g2psandbox:
  ph-ee-engine:
    zeebe:
      enabled: false
      broker:
        contactpoint: "zeebe-zeebe-gateway:26500"
    zeebe-cluster-helm:
      enabled: false

      elasticsearch:
        enabled: false
      kibana:
        enabled: false

    zeebe-operate-helm:
      enabled: false
      ingress:
        enabled: false 
        host: operate.sandbox.fynarfin.io 
      
    zeebe-gateway:
      enabled: false

    camunda-platform:
      enabled: false

    kibana:
      ingress:
      enabled: false
      className: "nginx"
      pathtype: "Prefix"
      annotations: {}
        # kubernetes.io/ingress.class: nginx
        # kubernetes.io/tls-acme: "true"       
      hosts:
        - host: analytics.sandbox.fynarfin.io
          paths:
            - path: / 
      
    ph_ee_connector_ams_mifos:
      enabled: false
      imageTag: v1.2.2 
      ingress:
        enabled: false 
        hosts:
          - host: ams-mifos.sandbox.fynarfin.io          
            paths: 
            - path: "/"
              backend:
                service:
                  name: ph-ee-connector-ams-mifos
                  port:
                    number: 80                   

    ph_ee_connector_mojaloop:
      enabled: false
      ingress:
        enabled: false  
        hosts:
          - host: mojaloop.sandbox.fynarfin.io          
            paths: 
            - path: "/"
              backend:
                service:
                  name: ph-ee-connector-mojaloop-java
                  port:
                    number: 80

    kafka:
      enabled: false

    channel:
      enabled: false
      server:
        ssl:
          keyPassword: "password"
          keyStorePassword: "password"   
      ingress:
        enabled: false 
        hosts:
          - host: channel.sandbox.fynarfin.io          
            paths: 
            - path: "/"
              backend:
                service:
                  name: "ph-ee-connector-channel"
                  port:
                    number: 8443
          - host: channel-gsma.sandbox.fynarfin.io          
            paths:          
            - path: "/"
              backend:
                service:
                  name: "ph-ee-connector-channel-gsma"
                  port:
                    number: 82 

    mockpayment:
      enabled: false

    elasticsearch:
      enabled: false

    camunda-platform-helm:
      enabled: false

    operations:
      mysql:
        enabled: false

    operations_app:
      enabled: false
      tenants: "rhino,gorilla"
      ingress:
        enabled: false 
        hosts:
          - host: ops-bk.sandbox.fynarfin.io          
            paths: 
            - path: "/"
              backend:
                service:
                  name: "ph-ee-operations-app"
                  port:
                    number: 80 

    operations_web:
      enabled: false 
      ingress:
        enabled: false
        annotations:
          kubernetes.io/ingress.class: "nginx"
        hosts:
          - host: ops.sandbox.fynarfin.io          
            paths: 
            - path: "/"
              backend:
                service:
                  name: "ph-ee-operations-web"
                  port:
                    number: 4200            

    ph_ee_connector_gsma:
      enabled: false
      ingress:
        enabled: false  

    ph_ee_connector_slcb:
      enabled: false
    
    mpesa:
      enabled: false
      
    roster_connector:
      enabled: false
      
    paygops_connector:
      enabled: false
      
    notifications:
      enabled: false
      NOTIFICATION_FAILURE_ENABLED: "false"
      ingress:
        enabled: false 
        hosts:
          - host: notifications.sandbox.fynarfin.io         
            paths: 
            - path: "/"
              backend:
                service:
                  name: "ph-ee-connector-notifications"
                  port:
                    number: 80 

    connector_bulk:
      enabled: false
      tenants: "rhino,gorilla"
      aws:
        region: "us-east-2"
        access_key: "AKIAX32JM37TZOJ5AKFB"
        secret_key: "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"
      operations_app:
        contactpoint: "https://ops-bk.sandbox.fynarfin.io/"
        endpoints:
          batch_transaction: "/api/v1/batch/transactions"  
      ingress:
        enabled: false
        annotations: 
          kubernetes.io/ingress.class: nginx  
        tls:
          - secretName: sandbox-secret
        hosts:
          - host: bulk-connector.sandbox.fynarfin.io     
            paths: 
            - path: "/"
              backend:
                service:
                  name: "ph-ee-connector-bulk"
                  port:
                    number: 80      
          
    zeebe_ops:
      enabled: false
      tenants: "rhino,gorilla"
      ingress:
        enabled: false 
        hosts:
          - host: zeebeops.sandbox.fynarfin.io          
            paths: 
            - path: "/"
              backend:
                service:
                  name: "ph-ee-zeebe-ops"
                  port:
                    number: 80

    messagegateway:
      enabled: false
      secret:
        value:
          api_key: "eKiC1_JWdKy7eaTGQFHxXXjXjacr60W9Zntl"
          project_id: "PJ5ff552ce01d2978c"
      ingress:
        enabled: false   
        hosts:
          - host: messagegateway.sandbox.fynarfin.io       
            paths: 
            - path: "/"
              backend:
                service:
                  name: "message-gateway"
                  port:
                    number: 80
                            
    importer_es:
      enabled: false

    importer_rdbms:
      enabled: false

    wildcardhostname: "*.sandbox.fynarfin.io"
    tls: ""

    keycloak:
      enabled: true
      ingress:
        enabled: true 
        ingressClassName: "kong"
        rules:
          - host: 'keycloak.sandbox.fynarfin.io'
            paths:
            - path: /
              pathType: Prefix
    
    kong:
      enabled: true
      image:
        repository: revomatico/docker-kong-oidc
        tag: "latest"
      env:
        plugins: "bundled,oidc"
        database: "postgres"
        pg_host: "security-postgresql" 
        pg_user: "keycloak"                  
        pg_password: "keycloak"
        pg_database: "kong"   
      admin:
        enabled: true
        http:
          enabled: true
        tls:
          enabled: false    
        ingress:
          enabled: true
          ingressClassName: "kong"
          hostname: kong-admin.sandbox.fynarfin.io
      extraObjects:
        - apiVersion: configuration.konghq.com/v1
          kind: KongClusterPlugin
          metadata:
            name: request-transformer
            annotations:
              kubernetes.io/ingress.class: "kong"
            labels:
              global: "true"
          disabled: false # optionally disable the plugin in Kong
          plugin: request-transformer
          config:
            remove:
              headers:
                - cookie
                - x-id-token
        - apiVersion: configuration.konghq.com/v1
          kind: KongClusterPlugin
          metadata:
            name: cors
            annotations:
              kubernetes.io/ingress.class: "kong"
            labels:
              global: "true"
          disabled: false # optionally disable the plugin in Kong
          plugin: cors
          config:
            origins:
              - "*"
            credentials: true
            max_age: 3600
            exposed_headers :
              - "X-Auth-Token"
            preflight_continue: false
        - apiVersion: configuration.konghq.com/v1
          kind: KongClusterPlugin
          metadata:
            name: oidc
            annotations:
              kubernetes.io/ingress.class: "kong"
            labels:
              global: "false"
          disabled: false # optionally disable the plugin in Kong
          plugin: oidc
          config: # configuration for the plugin
            client_id: kong-oidc
            client_secret: Z8ZDBn9W6j22H0Z3suBBJvzjzvf7xBPl  # Generated on keyCloak
            realm: Kong
            discovery: http://keycloak.sandbox.fynarfin.io/auth/realms/Kong/.well-known/openid-configuration
            scope: openid  
            introspection_endpoint: http://keycloak.sandbox.fynarfin.io/auth/realms/Kong/protocol/openid-connect/token/introspect
            redirect_after_logout_uri: http://keycloak.sandbox.fynarfin.io/auth/realms/kong-oidc/protocol/openid-connect/logout?redirect_uri=http://keycloak.sandbox.fynarfin.io
      migrations:
        preUpgrade: false
        postUpgrade: false


    redis:
      enabled: false
      replica:
        replicaCount: 0


hello-world:
  ingress:
    enabled: true
    className: "kong"
    hosts:
      - host: hello-world.sandbox.fynarfin.io
        paths:
          - path: /
            pathType: Prefix
    tls: []