annotations:
  artifacthub.io/changes: |
    - create optimize sub chart
  artifacthub.io/containsSecurityUpdates: "true"
apiVersion: v2
description: Optimize Helm Chart for Kubernetes
icon: https://helm.camunda.io/imgs/camunda.svg
name: optimize
version: 8.1.1
